spring:

  application:
    name: TimeWeave1
  datasource:
    url: jdbc:mysql://localhost:3306/timeweave_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: timdav-xUmquf-nisgo3
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template: true  # Validate that templates exist
    check-template-location: true  # Validate template location
    enabled: true  # Enable Thymeleaf view rendering
