spring:
  application:
    name: TimeWeave1

  datasource:
    url: jdbc:mysql://localhost:3306/timeweave_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: tw_user
    password: YourStrongP@ss
  jpa:
    hibernate:
      ddl-auto: create-drop  # Change this to 'update' or 'none' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template: true
    check-template-location: true
    enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: Abdallahi971222@gmail.com
    password: kdhpuwqarzfcumfp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:uploads/
