package com.timewave.timewave.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.Setter;

@Data
@Entity
public class Memory {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    private String title;
    private String description;
    private String date;
    private String location;
    private String mood;

    // Explicit setter for 'content' if needed
    // Content will store either text or the path of the photo
    private String content;
    // Setters and Getters generated by Lombok's @Data (unless you manually define them)
    // Type will be 'text' or 'photo'
    private String type;

    // Many memories can belong to one user
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    // Constructors
    public Memory() {}

    public Memory(String title, String description, String date, String location, String mood, String content, String type, User user) {
        this.title = title;
        this.description = description;
        this.date = date;
        this.location = location;
        this.mood = mood;
        this.content = content;
        this.type = type;
        this.user = user;
    }

    // Constructor without User
    public Memory(String title, String description, String date, String location, String mood, String content, String type) {
        this.title = title;
        this.description = description;
        this.date = date;
        this.location = location;
        this.mood = mood;
        this.content = content;
        this.type = type;
    }


    // You can also define a getter for 'content', but Lombok will do this automatically if you use @Data
}
